name: 'Hello World'
on: [push]
jobs:
  greeting:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello World action step
        id: hello
        uses: DevRadhy/hello-world-javascript-action@v1.0.0
        with:
          who-to-greet: 'John Doe'
      
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"